import assert from 'node:assert/strict';
export async function test({page,out}) {
 const results={};
 const snap=()=>page.evaluate(()=>window.__SOURCE_DEBUG__.snapshot());
 await page.locator('#enter-ground').click();
 await page.evaluate(()=>window.__SOURCE_DEBUG__.aimAt('frame-0-anchor-0'));
 await page.keyboard.press('KeyF');
 await page.waitForFunction(()=>window.__SOURCE_DEBUG__.snapshot().hook!==null);
 results.cast=await snap();assert(results.cast.source<100);assert.equal(results.cast.hook.bodyId,'frame-0-anchor-0');
 await page.keyboard.down('KeyQ');
 await page.waitForFunction(()=>window.__SOURCE_DEBUG__.snapshot().hook?.length<3.5,null,{timeout:45000});
 await page.keyboard.up('KeyQ');
 await page.keyboard.down('KeyD');await page.waitForTimeout(1400);await page.keyboard.up('KeyD');
 results.swing=await snap();assert(results.swing.player.position[1]>1.5,'reeling should lift player');
 await page.screenshot({path:`${out}/swinging.png`});
 const velocity=results.swing.player.velocity;
 await page.keyboard.press('KeyE');
 await page.waitForFunction(()=>!window.__SOURCE_DEBUG__.snapshot().hook);
 results.release=await snap();assert(Math.hypot(...results.release.player.velocity)>1,'release keeps motion');
 await page.locator('#reset-player').click();await page.waitForTimeout(500);
 await page.evaluate(()=>window.__SOURCE_DEBUG__.aimAt('crate-light'));
 await page.keyboard.press('KeyF');
 await page.waitForFunction(()=>window.__SOURCE_DEBUG__.snapshot().hook?.bodyId==='crate-light');
 await page.keyboard.down('KeyQ');
 await page.waitForFunction(()=>{const c=window.__SOURCE_DEBUG__.snapshot().objects.find(o=>o.id==='crate-light');return Math.hypot(c.position[0]-5,c.position[2]-5)>1.5;},null,{timeout:15000});
 await page.keyboard.up('KeyQ');
 results.pull=await snap();
 await page.evaluate(()=>window.__SOURCE_DEBUG__.simulation.source=.001);
 await page.waitForFunction(()=>window.__SOURCE_DEBUG__.snapshot().source===0&&!window.__SOURCE_DEBUG__.snapshot().hook);
 results.exhaustion=await snap();assert(results.exhaustion.weakened);
 await page.keyboard.press('KeyM');
 await page.waitForFunction(()=>window.__SOURCE_DEBUG__.snapshot().source>20);
 results.recovery=await snap();
 await page.locator('#creation-name').fill('Autosaved Tidehook');
 await page.locator('#reach').evaluate(el=>{el.value=32;el.dispatchEvent(new Event('input',{bubbles:true}));});
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('the-source.creation.v1'))?.name==='Autosaved Tidehook');
 results.designAutosave=await page.evaluate(()=>JSON.parse(localStorage.getItem('the-source.creation.v1')));
 assert.equal(results.designAutosave.reach,32);
 await page.locator('#enter-ground').click();
 const p0=(await snap()).player.position;
 await page.keyboard.down('KeyD');
 await page.waitForFunction(p=>{const n=window.__SOURCE_DEBUG__.snapshot().player.position;return Math.hypot(n[0]-p[0],n[2]-p[2])>2;},p0);
 await page.keyboard.up('KeyD');
 await page.waitForTimeout(3800);
 results.sessionAutosave=await page.evaluate(()=>JSON.parse(localStorage.getItem('the-source.session.v1')));
 await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>window.__SOURCE_DEBUG__);
 const restored=await snap();
 assert.equal(restored.creation.name,'Autosaved Tidehook');assert.equal(restored.creation.reach,32);
 const expected=results.sessionAutosave.position;
 assert(Math.hypot(restored.player.position[0]-expected[0],restored.player.position[2]-expected[2])<.5,'safe position restores');
 assert.equal(restored.hook,null);results.restored=restored;
 await page.locator('#minimap').click();assert(await page.locator('body').evaluate(el=>el.classList.contains('map-expanded')));
 assert((await page.locator('#minimap').boundingBox()).width>400);
 await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.body.classList.contains('map-expanded'));
 results.map=true;
 await page.setViewportSize({width:860,height:480});await page.screenshot({path:`${out}/landscape.png`});
 assert(await page.locator('#enter-ground').isVisible());
 await page.setViewportSize({width:1440,height:900});await page.screenshot({path:`${out}/final-meditation.png`});
 return results;
}
